import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form action="/send-data-here" method="post">
          <label for="label">Label:</label>
          <input type="text" id="label" name="label" required />

          <label for="idCampo">Id campo:</label>
          <input type="text" id="idCampo" name="idCampo" required />

          <label for="tipoCampo">Tipo campo:</label>

          <select id="tipoCampo" name="tipoCampo">
            <option value="a">Texto simples</option>
            <option value="b">Texto Grande</option>
            <option value="c">Combo</option>
          </select>

          <label for="texto">Texto:</label>
          <input type="text" id="texto" name="texto" required />

          <button type="submit">Cadastrar</button>
        </form>
      </main>
    </div>
  );
}
